
package DBTransferRegistrationClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "wsp_TransferRegistration_PortType", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/TransferRegistration")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WspTransferRegistrationPortType {


    /**
     * 
     * @param transferRegistrationRequest
     * @return
     *     returns DBTransferRegistrationClient.TransferRegistrationResponse
     * @throws Exception_Exception
     */
    @WebMethod(operationName = "ws_TransferRegistration", action = "DNB_WebServices_Providers_TransferRegistration_wsp_TransferRegistration_Binder_ws_TransferRegistration")
    @WebResult(name = "transferRegistrationResponse", targetNamespace = "")
    @RequestWrapper(localName = "ws_TransferRegistration", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/TransferRegistration", className = "DBTransferRegistrationClient.WsTransferRegistration")
    @ResponseWrapper(localName = "ws_TransferRegistrationResponse", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/TransferRegistration", className = "DBTransferRegistrationClient.WsTransferRegistrationResponse")
    public TransferRegistrationResponse wsTransferRegistration(
        @WebParam(name = "transferRegistrationRequest", targetNamespace = "")
        TransferRegistrationRequest transferRegistrationRequest)
        throws Exception_Exception
    ;

}
