
package DBTransferRegistrationClient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "wsp_TransferRegistration", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/TransferRegistration", wsdlLocation = "WSDL/TransferRegistration.wsdl")
public class WspTransferRegistration
    extends Service
{

    private final static URL WSPTRANSFERREGISTRATION_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(DBTransferRegistrationClient.WspTransferRegistration.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = DBTransferRegistrationClient.WspTransferRegistration.class.getResource("");
            url = new URL(baseUrl, "WSDL/TransferRegistration.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'WSDL/TransferRegistration.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSPTRANSFERREGISTRATION_WSDL_LOCATION = url;
    }

    public WspTransferRegistration(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WspTransferRegistration() {
        super(WSPTRANSFERREGISTRATION_WSDL_LOCATION, new QName("http://www.dnb.com/DNB_WebServices/Providers/TransferRegistration", "wsp_TransferRegistration"));
    }

    /**
     * 
     * @return
     *     returns WspTransferRegistrationPortType
     */
    @WebEndpoint(name = "DNB_WebServices_Providers_TransferRegistration_wsp_TransferRegistration_Port")
    public WspTransferRegistrationPortType getDNBWebServicesProvidersTransferRegistrationWspTransferRegistrationPort() {
        return super.getPort(new QName("http://www.dnb.com/DNB_WebServices/Providers/TransferRegistration", "DNB_WebServices_Providers_TransferRegistration_wsp_TransferRegistration_Port"), WspTransferRegistrationPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WspTransferRegistrationPortType
     */
    @WebEndpoint(name = "DNB_WebServices_Providers_TransferRegistration_wsp_TransferRegistration_Port")
    public WspTransferRegistrationPortType getDNBWebServicesProvidersTransferRegistrationWspTransferRegistrationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.dnb.com/DNB_WebServices/Providers/TransferRegistration", "DNB_WebServices_Providers_TransferRegistration_wsp_TransferRegistration_Port"), WspTransferRegistrationPortType.class, features);
    }

}
