
package ExperianTokenService;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * Experian Token Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TokenService", targetNamespace = "http://www.uk.experian.com/WASP/", wsdlLocation = "file:TokenService.wsdl")
public class TokenService
    extends Service
{

    private final static URL TOKENSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ExperianTokenService.TokenService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = ExperianTokenService.TokenService.class.getResource(".");
            url = new URL(baseUrl, "file:TokenService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/astacey/Experian/TokenService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TOKENSERVICE_WSDL_LOCATION = url;
    }

    public TokenService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TokenService() {
        super(TOKENSERVICE_WSDL_LOCATION, new QName("http://www.uk.experian.com/WASP/", "TokenService"));
    }

    /**
     * 
     * @return
     *     returns TokenServiceSoap
     */
    @WebEndpoint(name = "TokenServiceSoap")
    public TokenServiceSoap getTokenServiceSoap() {
        return super.getPort(new QName("http://www.uk.experian.com/WASP/", "TokenServiceSoap"), TokenServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TokenServiceSoap
     */
    @WebEndpoint(name = "TokenServiceSoap")
    public TokenServiceSoap getTokenServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.uk.experian.com/WASP/", "TokenServiceSoap"), TokenServiceSoap.class, features);
    }

}
