
package ExperianTokenService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "TokenServiceSoap", targetNamespace = "http://www.uk.experian.com/WASP/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TokenServiceSoap {


    /**
     * 
     * @param authenticationBlock
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "STS", action = "http://www.uk.experian.com/WASP/STS")
    @WebResult(name = "STSResult", targetNamespace = "http://www.uk.experian.com/WASP/")
    @RequestWrapper(localName = "STS", targetNamespace = "http://www.uk.experian.com/WASP/", className = "TokenService.STS")
    @ResponseWrapper(localName = "STSResponse", targetNamespace = "http://www.uk.experian.com/WASP/", className = "TokenService.STSResponse")
    public String sts(
        @WebParam(name = "authenticationBlock", targetNamespace = "http://www.uk.experian.com/WASP/")
        String authenticationBlock);

    /**
     * 
     * @param application
     * @param checkIP
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LoginWithCertificate", action = "http://www.uk.experian.com/WASP/LoginWithCertificate")
    @WebResult(name = "LoginWithCertificateResult", targetNamespace = "http://www.uk.experian.com/WASP/")
    @RequestWrapper(localName = "LoginWithCertificate", targetNamespace = "http://www.uk.experian.com/WASP/", className = "TokenService.LoginWithCertificate")
    @ResponseWrapper(localName = "LoginWithCertificateResponse", targetNamespace = "http://www.uk.experian.com/WASP/", className = "TokenService.LoginWithCertificateResponse")
    public String loginWithCertificate(
        @WebParam(name = "application", targetNamespace = "http://www.uk.experian.com/WASP/")
        String application,
        @WebParam(name = "checkIP", targetNamespace = "http://www.uk.experian.com/WASP/")
        boolean checkIP);

    /**
     * 
     * @param username
     * @param application
     * @param checkIP
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LoginWithUsernamePassword", action = "http://www.uk.experian.com/WASP/LoginWithUsernamePassword")
    @WebResult(name = "LoginWithUsernamePasswordResult", targetNamespace = "http://www.uk.experian.com/WASP/")
    @RequestWrapper(localName = "LoginWithUsernamePassword", targetNamespace = "http://www.uk.experian.com/WASP/", className = "TokenService.LoginWithUsernamePassword")
    @ResponseWrapper(localName = "LoginWithUsernamePasswordResponse", targetNamespace = "http://www.uk.experian.com/WASP/", className = "TokenService.LoginWithUsernamePasswordResponse")
    public String loginWithUsernamePassword(
        @WebParam(name = "application", targetNamespace = "http://www.uk.experian.com/WASP/")
        String application,
        @WebParam(name = "username", targetNamespace = "http://www.uk.experian.com/WASP/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://www.uk.experian.com/WASP/")
        String password,
        @WebParam(name = "checkIP", targetNamespace = "http://www.uk.experian.com/WASP/")
        boolean checkIP);

}
