
package ExperianAlertsAddRemoveWS;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AlertsAddRemove", targetNamespace = "http://services.experian.com/experian/wbsv/generic/bi", wsdlLocation = "file:/home/astacey/git/DnBImporter/DnBImporter/ExperianWSDL/AlertsAddRemove.wsdl")
public class AlertsAddRemove
    extends Service
{

    private final static URL ALERTSADDREMOVE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ExperianAlertsAddRemoveWS.AlertsAddRemove.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = ExperianAlertsAddRemoveWS.AlertsAddRemove.class.getResource(".");
            url = new URL(baseUrl, "file:/home/astacey/git/DnBImporter/DnBImporter/ExperianWSDL/AlertsAddRemove.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/astacey/git/DnBImporter/DnBImporter/ExperianWSDL/AlertsAddRemove.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ALERTSADDREMOVE_WSDL_LOCATION = url;
    }

    public AlertsAddRemove(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AlertsAddRemove() {
        super(ALERTSADDREMOVE_WSDL_LOCATION, new QName("http://services.experian.com/experian/wbsv/generic/bi", "AlertsAddRemove"));
    }

    /**
     * 
     * @return
     *     returns ExperianUKBIServicesCoreIServices
     */
    @WebEndpoint(name = "AddRemoveAlertBusiness")
    public ExperianUKBIServicesCoreIServices getAddRemoveAlertBusiness() {
        return super.getPort(new QName("http://services.experian.com/experian/wbsv/generic/bi", "AddRemoveAlertBusiness"), ExperianUKBIServicesCoreIServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExperianUKBIServicesCoreIServices
     */
    @WebEndpoint(name = "AddRemoveAlertBusiness")
    public ExperianUKBIServicesCoreIServices getAddRemoveAlertBusiness(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.experian.com/experian/wbsv/generic/bi", "AddRemoveAlertBusiness"), ExperianUKBIServicesCoreIServices.class, features);
    }

}
