
package DBFullReportsClient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DNBWebService", targetNamespace = "http://gateway.dnb.com/getProduct", wsdlLocation = "file:/home/astacey/git/DnBImporter/DnBImporter/DnBWebServiceAccess/DBFullReportsClient/WSDL/DNBWebServiceGateway.wsdl")
public class DNBWebService
    extends Service
{

    private final static URL DNBWEBSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(DBFullReportsClient.DNBWebService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = DBFullReportsClient.DNBWebService.class.getResource(".");
            url = new URL(baseUrl, "file:/home/astacey/git/DnBImporter/DnBImporter/DnBWebServiceAccess/DBFullReportsClient/WSDL/DNBWebServiceGateway.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/astacey/git/DnBImporter/DnBImporter/DnBWebServiceAccess/DBFullReportsClient/WSDL/DNBWebServiceGateway.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DNBWEBSERVICE_WSDL_LOCATION = url;
    }

    public DNBWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DNBWebService() {
        super(DNBWEBSERVICE_WSDL_LOCATION, new QName("http://gateway.dnb.com/getProduct", "DNBWebService"));
    }

    /**
     * 
     * @return
     *     returns DNBWebServicingPortType
     */
    @WebEndpoint(name = "DNBWebServicingPort")
    public DNBWebServicingPortType getDNBWebServicingPort() {
        return super.getPort(new QName("http://gateway.dnb.com/getProduct", "DNBWebServicingPort"), DNBWebServicingPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DNBWebServicingPortType
     */
    @WebEndpoint(name = "DNBWebServicingPort")
    public DNBWebServicingPortType getDNBWebServicingPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://gateway.dnb.com/getProduct", "DNBWebServicingPort"), DNBWebServicingPortType.class, features);
    }

}
