
package DBFullReportsClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DNBWebServicingPortType", targetNamespace = "http://gateway.dnb.com/getProduct")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DNBWebServicingPortType {


    /**
     * 
     * @param inparams
     * @return
     *     returns DBFullReportsClient.FindBusinessResponse
     */
    @WebMethod(action = "http://gateway.dnb.com/getProduct")
    @WebResult(name = "FindBusinessResponse", targetNamespace = "http://gateway.dnb.com/getProduct", partName = "inparams")
    public FindBusinessResponse findBusiness(
        @WebParam(name = "FindBusinessRequest", targetNamespace = "http://gateway.dnb.com/getProduct", partName = "inparams")
        FindBusinessRequest inparams);

    /**
     * 
     * @param inparams
     * @return
     *     returns DBFullReportsClient.GetModularProductResponse
     */
    @WebMethod(action = "http://gateway.dnb.com/getProduct")
    @WebResult(name = "getModularProductResponse", targetNamespace = "http://gateway.dnb.com/getProduct", partName = "inparams")
    public GetModularProductResponse getModularProduct(
        @WebParam(name = "getModularProductRequest", targetNamespace = "http://gateway.dnb.com/getProduct", partName = "inparams")
        GetModularProductRequest inparams);

    /**
     * 
     * @param inparams
     * @return
     *     returns DBFullReportsClient.GetProductResponse
     */
    @WebMethod(action = "http://gateway.dnb.com/getProduct")
    @WebResult(name = "getProductResponse", targetNamespace = "http://gateway.dnb.com/getProduct", partName = "inparams")
    public GetProductResponse getProduct(
        @WebParam(name = "getProductRequest", targetNamespace = "http://gateway.dnb.com/getProduct", partName = "inparams")
        GetProductRequest inparams);

    /**
     * 
     * @param inparams
     * @return
     *     returns DBFullReportsClient.MonitoringResponseType
     */
    @WebMethod(action = "http://gateway.dnb.com/getProduct")
    @WebResult(name = "RegisterForMonitoringResponse", targetNamespace = "http://gateway.dnb.com/getProduct", partName = "inparams")
    public MonitoringResponseType addMonitoring(
        @WebParam(name = "RegisterForMonitoringRequest", targetNamespace = "http://gateway.dnb.com/getProduct", partName = "inparams")
        RegisterForMonitoringRequest inparams);

    /**
     * 
     * @param inparams
     * @return
     *     returns DBFullReportsClient.GetDocumentOrderResponse
     */
    @WebMethod(action = "http://gateway.dnb.com/getProduct")
    @WebResult(name = "getDocumentOrderResponse", targetNamespace = "http://gateway.dnb.com/getProduct", partName = "inparams")
    public GetDocumentOrderResponse getDocumentOrder(
        @WebParam(name = "getDocumentOrderRequest", targetNamespace = "http://gateway.dnb.com/getProduct", partName = "inparams")
        GetDocumentOrderRequest inparams);

    /**
     * 
     * @param inparams
     * @return
     *     returns DBFullReportsClient.GetDocumentAvailabilityResponse
     */
    @WebMethod(action = "http://gateway.dnb.com/getProduct")
    @WebResult(name = "getDocumentAvailabilityResponse", targetNamespace = "http://gateway.dnb.com/getProduct", partName = "inparams")
    public GetDocumentAvailabilityResponse getDocumentAvailability(
        @WebParam(name = "getDocumentAvailabilityRequest", targetNamespace = "http://gateway.dnb.com/getProduct", partName = "inparams")
        GetDocumentAvailabilityRequest inparams);

    /**
     * 
     * @param inparams
     * @return
     *     returns DBFullReportsClient.MonitoringResponseType
     */
    @WebMethod(action = "http://gateway.dnb.com/getProduct")
    @WebResult(name = "CancelMonitoringResponse", targetNamespace = "http://gateway.dnb.com/getProduct", partName = "inparams")
    public MonitoringResponseType cancelMonitoring(
        @WebParam(name = "CancelMonitoringRequest", targetNamespace = "http://gateway.dnb.com/getProduct", partName = "inparams")
        CancelMonitoringRequest inparams);

    /**
     * 
     * @param inparams
     * @return
     *     returns DBFullReportsClient.RetrieveMonitoringListResponse
     */
    @WebMethod(action = "http://gateway.dnb.com/getProduct")
    @WebResult(name = "RetrieveMonitoringListResponse", targetNamespace = "http://gateway.dnb.com/getProduct", partName = "inparams")
    public RetrieveMonitoringListResponse retrieveMonitoringList(
        @WebParam(name = "RetrieveMonitoringListRequest", targetNamespace = "http://gateway.dnb.com/getProduct", partName = "inparams")
        RetrieveMonitoringListRequest inparams);

    /**
     * 
     * @param inparams
     * @return
     *     returns DBFullReportsClient.ModifyPasswordResponse
     */
    @WebMethod(action = "http://gateway.dnb.com/getProduct")
    @WebResult(name = "modifyPasswordResponse", targetNamespace = "http://gateway.dnb.com/getProduct", partName = "inparams")
    public ModifyPasswordResponse modifyPassword(
        @WebParam(name = "modifyPasswordRequest", targetNamespace = "http://gateway.dnb.com/getProduct", partName = "inparams")
        ModifyPasswordRequest inparams);

}
