
package DBGetNotificationsClientV3;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "wsp_GetNotifications_V3_PortType", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/GetNotifications_V3/wsp_GetNotifications_V3")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WspGetNotificationsV3PortType {


    /**
     * 
     * @param getNotificationsRequest
     * @return
     *     returns DBGetNotificationsClientV3.GetNotificationsResponse
     */
    @WebMethod(operationName = "ws_GetNotifications", action = "DNB_WebServices_Providers_GetNotifications_V3_wsp_GetNotifications_V3_Binder_ws_GetNotifications")
    @WebResult(name = "getNotificationsResponse", targetNamespace = "")
    @RequestWrapper(localName = "ws_GetNotifications", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/GetNotifications_V3/wsp_GetNotifications_V3", className = "DBGetNotificationsClientV3.WsGetNotifications")
    @ResponseWrapper(localName = "ws_GetNotificationsResponse", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/GetNotifications_V3/wsp_GetNotifications_V3", className = "DBGetNotificationsClientV3.WsGetNotificationsResponse")
    public GetNotificationsResponse wsGetNotifications(
        @WebParam(name = "getNotificationsRequest", targetNamespace = "")
        GetNotificationsRequest getNotificationsRequest);

}
