
package ExperianAlertsRequestWS;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Experian.UK.BI.Services.Core.IServices", targetNamespace = "http://services.experian.com/experian/wbsv/generic/bi")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExperianUKBIServicesCoreIServices {


    /**
     * 
     * @param alertsMessageInput
     * @return
     *     returns ExperianAlertsRequestWS.AlertsMessageOutput
     */
    @WebMethod(operationName = "RequestAlert", action = "http://services.experian.com/experian/wbsv/generic/bi/Experian.UK.BI.Services.Core.IServices/RequestAlert")
    @WebResult(name = "AlertsMessageOutput", targetNamespace = "http://schema.uk.experian.com/experian/bi/alertsrequest/intr/v100/alertsrequest", partName = "AlertsMessageOutput")
    public AlertsMessageOutput requestAlert(
        @WebParam(name = "AlertsMessageInput", targetNamespace = "http://schema.uk.experian.com/experian/bi/alertsrequest/intr/v100/alertsrequest", partName = "AlertsMessageInput")
        AlertsMessageInput alertsMessageInput);

}
