
package DBGDPV3;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "wsp_GDP_V3_PortType", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/OrderAndInvestigations/GDP_V3/wsp_GDP_V3")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WspGDPV3PortType {


    /**
     * 
     * @param corporateLinkageRequest
     * @return
     *     returns DBGDPV3.CorporateLinkageResponse
     */
    @WebMethod(operationName = "ws_CorporateLinkage", action = "DNB_WebServices_Providers_OrderAndInvestigations_GDP_V3_wsp_GDP_V3_Binder_ws_CorporateLinkage")
    @WebResult(name = "corporateLinkageResponse", targetNamespace = "")
    @RequestWrapper(localName = "ws_CorporateLinkage", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/OrderAndInvestigations/GDP_V3/wsp_GDP_V3", className = "DBGDPV3.WsCorporateLinkage")
    @ResponseWrapper(localName = "ws_CorporateLinkageResponse", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/OrderAndInvestigations/GDP_V3/wsp_GDP_V3", className = "DBGDPV3.WsCorporateLinkageResponse")
    public CorporateLinkageResponse wsCorporateLinkage(
        @WebParam(name = "corporateLinkageRequest", targetNamespace = "")
        ProdOrderRequest3 corporateLinkageRequest);

    /**
     * 
     * @param gdmRequest
     * @return
     *     returns DBGDPV3.GDMResponse
     */
    @WebMethod(operationName = "ws_GDM", action = "DNB_WebServices_Providers_OrderAndInvestigations_GDP_V3_wsp_GDP_V3_Binder_ws_GDM")
    @WebResult(name = "gdmResponse", targetNamespace = "")
    @RequestWrapper(localName = "ws_GDM", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/OrderAndInvestigations/GDP_V3/wsp_GDP_V3", className = "DBGDPV3.WsGDM")
    @ResponseWrapper(localName = "ws_GDMResponse", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/OrderAndInvestigations/GDP_V3/wsp_GDP_V3", className = "DBGDPV3.WsGDMResponse")
    public GDMResponse wsGDM(
        @WebParam(name = "gdmRequest", targetNamespace = "")
        ProdOrderRequest3 gdmRequest);

    /**
     * 
     * @param globalProdERamRequest
     * @return
     *     returns DBGDPV3.GlobalProdEramResponse
     */
    @WebMethod(operationName = "ws_GlobalProduct_eRam", action = "DNB_WebServices_Providers_OrderAndInvestigations_GDP_V3_wsp_GDP_V3_Binder_ws_GlobalProduct_eRam")
    @WebResult(name = "globalProd_eRamResponse", targetNamespace = "")
    @RequestWrapper(localName = "ws_GlobalProduct_eRam", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/OrderAndInvestigations/GDP_V3/wsp_GDP_V3", className = "DBGDPV3.WsGlobalProductERam")
    @ResponseWrapper(localName = "ws_GlobalProduct_eRamResponse", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/OrderAndInvestigations/GDP_V3/wsp_GDP_V3", className = "DBGDPV3.WsGlobalProductERamResponse")
    public GlobalProdEramResponse wsGlobalProductERam(
        @WebParam(name = "globalProd_eRamRequest", targetNamespace = "")
        ProdOrderRequest3 globalProdERamRequest);

    /**
     * 
     * @param gdpRequest
     * @return
     *     returns DBGDPV3.GDPResponse
     */
    @WebMethod(operationName = "ws_OtherGDPProducts", action = "DNB_WebServices_Providers_OrderAndInvestigations_GDP_V3_wsp_GDP_V3_Binder_ws_OtherGDPProducts")
    @WebResult(name = "GDPResponse", targetNamespace = "")
    @RequestWrapper(localName = "ws_OtherGDPProducts", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/OrderAndInvestigations/GDP_V3/wsp_GDP_V3", className = "DBGDPV3.WsOtherGDPProducts")
    @ResponseWrapper(localName = "ws_OtherGDPProductsResponse", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/OrderAndInvestigations/GDP_V3/wsp_GDP_V3", className = "DBGDPV3.WsOtherGDPProductsResponse")
    public GDPResponse wsOtherGDPProducts(
        @WebParam(name = "GDPRequest", targetNamespace = "")
        ProdOrderRequest3 gdpRequest);

}
