
package DBGDPV3;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "wsp_GDP_V3", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/OrderAndInvestigations/GDP_V3/wsp_GDP_V3", wsdlLocation = "file:WSDL/GDP_V3.wsdl")
public class WspGDPV3
    extends Service
{

    private final static URL WSPGDPV3_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(DBGDPV3.WspGDPV3 .class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = DBGDPV3.WspGDPV3 .class.getResource(".");
            url = new URL(baseUrl, "file:WSDL/GDP_V3.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:WSDL/GDP_V3.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSPGDPV3_WSDL_LOCATION = url;
    }

    public WspGDPV3(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WspGDPV3() {
        super(WSPGDPV3_WSDL_LOCATION, new QName("http://www.dnb.com/DNB_WebServices/Providers/OrderAndInvestigations/GDP_V3/wsp_GDP_V3", "wsp_GDP_V3"));
    }

    /**
     * 
     * @return
     *     returns WspGDPV3PortType
     */
    @WebEndpoint(name = "DNB_WebServices_Providers_OrderAndInvestigations_GDP_V3_wsp_GDP_V3_Port")
    public WspGDPV3PortType getDNBWebServicesProvidersOrderAndInvestigationsGDPV3WspGDPV3Port() {
        return super.getPort(new QName("http://www.dnb.com/DNB_WebServices/Providers/OrderAndInvestigations/GDP_V3/wsp_GDP_V3", "DNB_WebServices_Providers_OrderAndInvestigations_GDP_V3_wsp_GDP_V3_Port"), WspGDPV3PortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WspGDPV3PortType
     */
    @WebEndpoint(name = "DNB_WebServices_Providers_OrderAndInvestigations_GDP_V3_wsp_GDP_V3_Port")
    public WspGDPV3PortType getDNBWebServicesProvidersOrderAndInvestigationsGDPV3WspGDPV3Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.dnb.com/DNB_WebServices/Providers/OrderAndInvestigations/GDP_V3/wsp_GDP_V3", "DNB_WebServices_Providers_OrderAndInvestigations_GDP_V3_wsp_GDP_V3_Port"), WspGDPV3PortType.class, features);
    }

}
