
package DBModifyRegistrationClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "wsp_ModifyRegistration_PortType", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/ModifyRegistration")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WspModifyRegistrationPortType {


    /**
     * 
     * @param modifyRegistrationRequest
     * @return
     *     returns DBModifyRegistrationClient.ModifyRegistrationResponse
     * @throws Exception_Exception
     */
    @WebMethod(operationName = "ws_ModifyRegistration", action = "DNB_WebServices_Providers_ModifyRegistration_wsp_ModifyRegistration_Binder_ws_ModifyRegistration")
    @WebResult(name = "modifyRegistrationResponse", targetNamespace = "")
    @RequestWrapper(localName = "ws_ModifyRegistration", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/ModifyRegistration", className = "DBModifyRegistrationClient.WsModifyRegistration")
    @ResponseWrapper(localName = "ws_ModifyRegistrationResponse", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/ModifyRegistration", className = "DBModifyRegistrationClient.WsModifyRegistrationResponse")
    public ModifyRegistrationResponse wsModifyRegistration(
        @WebParam(name = "modifyRegistrationRequest", targetNamespace = "")
        ModifyRegistrationRequest modifyRegistrationRequest)
        throws Exception_Exception
    ;

}
