
package DBModifyRegistrationClient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "wsp_ModifyRegistration", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/ModifyRegistration", wsdlLocation = "WSDL/ModifyRegistration.wsdl")
public class WspModifyRegistration
    extends Service
{

    private final static URL WSPMODIFYREGISTRATION_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(DBModifyRegistrationClient.WspModifyRegistration.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = DBModifyRegistrationClient.WspModifyRegistration.class.getResource("");
            url = new URL(baseUrl, "WSDL/ModifyRegistration.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'WSDL/ModifyRegistration.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSPMODIFYREGISTRATION_WSDL_LOCATION = url;
    }

    public WspModifyRegistration(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WspModifyRegistration() {
        super(WSPMODIFYREGISTRATION_WSDL_LOCATION, new QName("http://www.dnb.com/DNB_WebServices/Providers/ModifyRegistration", "wsp_ModifyRegistration"));
    }

    /**
     * 
     * @return
     *     returns WspModifyRegistrationPortType
     */
    @WebEndpoint(name = "DNB_WebServices_Providers_ModifyRegistration_wsp_ModifyRegistration_Port")
    public WspModifyRegistrationPortType getDNBWebServicesProvidersModifyRegistrationWspModifyRegistrationPort() {
        return super.getPort(new QName("http://www.dnb.com/DNB_WebServices/Providers/ModifyRegistration", "DNB_WebServices_Providers_ModifyRegistration_wsp_ModifyRegistration_Port"), WspModifyRegistrationPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WspModifyRegistrationPortType
     */
    @WebEndpoint(name = "DNB_WebServices_Providers_ModifyRegistration_wsp_ModifyRegistration_Port")
    public WspModifyRegistrationPortType getDNBWebServicesProvidersModifyRegistrationWspModifyRegistrationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.dnb.com/DNB_WebServices/Providers/ModifyRegistration", "DNB_WebServices_Providers_ModifyRegistration_wsp_ModifyRegistration_Port"), WspModifyRegistrationPortType.class, features);
    }

}
