
package DBBIRClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "wsp_BIR_V1_PortType", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/OrderAndInvestigations/OtherProducts/BIR_V1/wsp_BIR_V1")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WspBIRV1PortType {


    /**
     * 
     * @param birRequest
     * @return
     *     returns DBBIRClient.BIRResponse
     */
    @WebMethod(operationName = "ws_BIR", action = "DNB_WebServices_Providers_OrderAndInvestigations_OtherProducts_BIR_V1_wsp_BIR_V1_Binder_ws_BIR")
    @WebResult(name = "BIRResponse", targetNamespace = "")
    @RequestWrapper(localName = "ws_BIR", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/OrderAndInvestigations/OtherProducts/BIR_V1/wsp_BIR_V1", className = "DBBIRClient.WsBIR")
    @ResponseWrapper(localName = "ws_BIRResponse", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/OrderAndInvestigations/OtherProducts/BIR_V1/wsp_BIR_V1", className = "DBBIRClient.WsBIRResponse")
    public BIRResponse wsBIR(
        @WebParam(name = "BIRRequest", targetNamespace = "")
        ProdOrderRequest2 birRequest);

}
