
package DBBIRClient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "wsp_BIR_V1", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/OrderAndInvestigations/OtherProducts/BIR_V1/wsp_BIR_V1", wsdlLocation = "WSDL/BIR.wsdl")
public class WspBIRV1
    extends Service
{

    private final static URL WSPBIRV1_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(DBBIRClient.WspBIRV1 .class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = DBBIRClient.WspBIRV1 .class.getResource("");
            url = new URL(baseUrl, "WSDL/BIR.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'WSDL/BIR.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSPBIRV1_WSDL_LOCATION = url;
    }

    public WspBIRV1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WspBIRV1() {
        super(WSPBIRV1_WSDL_LOCATION, new QName("http://www.dnb.com/DNB_WebServices/Providers/OrderAndInvestigations/OtherProducts/BIR_V1/wsp_BIR_V1", "wsp_BIR_V1"));
    }

    /**
     * 
     * @return
     *     returns WspBIRV1PortType
     */
    @WebEndpoint(name = "DNB_WebServices_Providers_OrderAndInvestigations_OtherProducts_BIR_V1_wsp_BIR_V1_Port")
    public WspBIRV1PortType getDNBWebServicesProvidersOrderAndInvestigationsOtherProductsBIRV1WspBIRV1Port() {
        return super.getPort(new QName("http://www.dnb.com/DNB_WebServices/Providers/OrderAndInvestigations/OtherProducts/BIR_V1/wsp_BIR_V1", "DNB_WebServices_Providers_OrderAndInvestigations_OtherProducts_BIR_V1_wsp_BIR_V1_Port"), WspBIRV1PortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WspBIRV1PortType
     */
    @WebEndpoint(name = "DNB_WebServices_Providers_OrderAndInvestigations_OtherProducts_BIR_V1_wsp_BIR_V1_Port")
    public WspBIRV1PortType getDNBWebServicesProvidersOrderAndInvestigationsOtherProductsBIRV1WspBIRV1Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.dnb.com/DNB_WebServices/Providers/OrderAndInvestigations/OtherProducts/BIR_V1/wsp_BIR_V1", "DNB_WebServices_Providers_OrderAndInvestigations_OtherProducts_BIR_V1_wsp_BIR_V1_Port"), WspBIRV1PortType.class, features);
    }

}
