
package DBGetRegistrationActivityClient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "wsp_GetRegistrationActivity", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/GetRegistrationActivity", wsdlLocation = "file:WSDL/GetRegistrationActivity.wsdl")
public class WspGetRegistrationActivity
    extends Service
{

    private final static URL WSPGETREGISTRATIONACTIVITY_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(DBGetRegistrationActivityClient.WspGetRegistrationActivity.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = DBGetRegistrationActivityClient.WspGetRegistrationActivity.class.getResource(".");
            url = new URL(baseUrl, "file:WSDL/GetRegistrationActivity.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:WSDL/GetRegistrationActivity.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSPGETREGISTRATIONACTIVITY_WSDL_LOCATION = url;
    }

    public WspGetRegistrationActivity(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WspGetRegistrationActivity() {
        super(WSPGETREGISTRATIONACTIVITY_WSDL_LOCATION, new QName("http://www.dnb.com/DNB_WebServices/Providers/GetRegistrationActivity", "wsp_GetRegistrationActivity"));
    }

    /**
     * 
     * @return
     *     returns WspGetRegistrationActivityPortType
     */
    @WebEndpoint(name = "DNB_WebServices_Providers_GetRegistrationActivity_wsp_GetRegistrationActivity_Port")
    public WspGetRegistrationActivityPortType getDNBWebServicesProvidersGetRegistrationActivityWspGetRegistrationActivityPort() {
        return super.getPort(new QName("http://www.dnb.com/DNB_WebServices/Providers/GetRegistrationActivity", "DNB_WebServices_Providers_GetRegistrationActivity_wsp_GetRegistrationActivity_Port"), WspGetRegistrationActivityPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WspGetRegistrationActivityPortType
     */
    @WebEndpoint(name = "DNB_WebServices_Providers_GetRegistrationActivity_wsp_GetRegistrationActivity_Port")
    public WspGetRegistrationActivityPortType getDNBWebServicesProvidersGetRegistrationActivityWspGetRegistrationActivityPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.dnb.com/DNB_WebServices/Providers/GetRegistrationActivity", "DNB_WebServices_Providers_GetRegistrationActivity_wsp_GetRegistrationActivity_Port"), WspGetRegistrationActivityPortType.class, features);
    }

}
