
package DBGetRegistrationActivityClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "wsp_GetRegistrationActivity_PortType", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/GetRegistrationActivity")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WspGetRegistrationActivityPortType {


    /**
     * 
     * @param getRegistrationActivityRequest
     * @return
     *     returns DBGetRegistrationActivityClient.GetRegistrationActivityResponse
     * @throws Exception_Exception
     */
    @WebMethod(operationName = "ws_GetRegistrationActivity", action = "DNB_WebServices_Providers_GetRegistrationActivity_wsp_GetRegistrationActivity_Binder_ws_GetRegistrationActivity")
    @WebResult(name = "getRegistrationActivityResponse", targetNamespace = "")
    @RequestWrapper(localName = "ws_GetRegistrationActivity", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/GetRegistrationActivity", className = "DBGetRegistrationActivityClient.WsGetRegistrationActivity")
    @ResponseWrapper(localName = "ws_GetRegistrationActivityResponse", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/GetRegistrationActivity", className = "DBGetRegistrationActivityClient.WsGetRegistrationActivityResponse")
    public GetRegistrationActivityResponse wsGetRegistrationActivity(
        @WebParam(name = "getRegistrationActivityRequest", targetNamespace = "")
        GetRegistrationActivityRequest getRegistrationActivityRequest)
        throws Exception_Exception
    ;

}
