
package DBGetNotificationsClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "wsp_GetNotifications_PortType", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/GetNotifications")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WspGetNotificationsPortType {


    /**
     * 
     * @param getNotificationsRequest
     * @return
     *     returns DBGetNotificationsClient.GetNotificationsResponse
     * @throws Exception_Exception
     */
    @WebMethod(operationName = "ws_GetNotifications", action = "DNB_WebServices_Providers_GetNotifications_wsp_GetNotifications_Binder_ws_GetNotifications")
    @WebResult(name = "getNotificationsResponse", targetNamespace = "")
    @RequestWrapper(localName = "ws_GetNotifications", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/GetNotifications", className = "DBGetNotificationsClient.WsGetNotifications")
    @ResponseWrapper(localName = "ws_GetNotificationsResponse", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/GetNotifications", className = "DBGetNotificationsClient.WsGetNotificationsResponse")
    public GetNotificationsResponse wsGetNotifications(
        @WebParam(name = "getNotificationsRequest", targetNamespace = "")
        GetNotificationsRequest getNotificationsRequest)
        throws Exception_Exception
    ;

}
