
package DBGetRegistrationListClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "wsp_GetRegistrationList_PortType", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/GetRegistrationList")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WspGetRegistrationListPortType {


    /**
     * 
     * @param getRegistrationListRequest
     * @return
     *     returns DBGetRegistrationListClient.GetRegistrationListResponse
     */
    @WebMethod(operationName = "ws_GetRegistrationList", action = "DNB_WebServices_Providers_GetRegistrationList_wsp_GetRegistrationList_Binder_ws_GetRegistrationList")
    @WebResult(name = "getRegistrationListResponse", targetNamespace = "")
    @RequestWrapper(localName = "ws_GetRegistrationList", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/GetRegistrationList", className = "DBGetRegistrationListClient.WsGetRegistrationList")
    @ResponseWrapper(localName = "ws_GetRegistrationListResponse", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/GetRegistrationList", className = "DBGetRegistrationListClient.WsGetRegistrationListResponse")
    public GetRegistrationListResponse wsGetRegistrationList(
        @WebParam(name = "getRegistrationListRequest", targetNamespace = "")
        GetRegistrationListRequest getRegistrationListRequest);

}
