
package DBAddRegistrationClientV1;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "wsp_AddRegistration_V1", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/AddRegistration_V1/wsp_AddRegistration_V1", wsdlLocation = "file:WSDL/AddRegistration_V1.wsdl")
public class WspAddRegistrationV1
    extends Service
{

    private final static URL WSPADDREGISTRATIONV1_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(DBAddRegistrationClientV1.WspAddRegistrationV1 .class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = DBAddRegistrationClientV1.WspAddRegistrationV1 .class.getResource(".");
            url = new URL(baseUrl, "file:WSDL/AddRegistration_V1.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:WSDL/AddRegistration_V1.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSPADDREGISTRATIONV1_WSDL_LOCATION = url;
    }

    public WspAddRegistrationV1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WspAddRegistrationV1() {
        super(WSPADDREGISTRATIONV1_WSDL_LOCATION, new QName("http://www.dnb.com/DNB_WebServices/Providers/AddRegistration_V1/wsp_AddRegistration_V1", "wsp_AddRegistration_V1"));
    }

    /**
     * 
     * @return
     *     returns WspAddRegistrationV1PortType
     */
    @WebEndpoint(name = "DNB_WebServices_Providers_AddRegistration_V1_wsp_AddRegistration_V1_Port")
    public WspAddRegistrationV1PortType getDNBWebServicesProvidersAddRegistrationV1WspAddRegistrationV1Port() {
        return super.getPort(new QName("http://www.dnb.com/DNB_WebServices/Providers/AddRegistration_V1/wsp_AddRegistration_V1", "DNB_WebServices_Providers_AddRegistration_V1_wsp_AddRegistration_V1_Port"), WspAddRegistrationV1PortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WspAddRegistrationV1PortType
     */
    @WebEndpoint(name = "DNB_WebServices_Providers_AddRegistration_V1_wsp_AddRegistration_V1_Port")
    public WspAddRegistrationV1PortType getDNBWebServicesProvidersAddRegistrationV1WspAddRegistrationV1Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.dnb.com/DNB_WebServices/Providers/AddRegistration_V1/wsp_AddRegistration_V1", "DNB_WebServices_Providers_AddRegistration_V1_wsp_AddRegistration_V1_Port"), WspAddRegistrationV1PortType.class, features);
    }

}
