
package DBAddRegistrationClientV1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "wsp_AddRegistration_V1_PortType", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/AddRegistration_V1/wsp_AddRegistration_V1")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WspAddRegistrationV1PortType {


    /**
     * 
     * @param addRegistrationRequest
     * @return
     *     returns DBAddRegistrationClientV1.AddRegistrationResponse
     */
    @WebMethod(operationName = "ws_AddRegistration", action = "DNB_WebServices_Providers_AddRegistration_V1_wsp_AddRegistration_V1_Binder_ws_AddRegistration")
    @WebResult(name = "addRegistrationResponse", targetNamespace = "")
    @RequestWrapper(localName = "ws_AddRegistration", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/AddRegistration_V1/wsp_AddRegistration_V1", className = "DBAddRegistrationClientV1.WsAddRegistration")
    @ResponseWrapper(localName = "ws_AddRegistrationResponse", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/AddRegistration_V1/wsp_AddRegistration_V1", className = "DBAddRegistrationClientV1.WsAddRegistrationResponse")
    public AddRegistrationResponse wsAddRegistration(
        @WebParam(name = "addRegistrationRequest", targetNamespace = "")
        AddRegistrationRequest addRegistrationRequest);

}
