
package DBGetNotificationCountClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "wsp_GetNotificationCount_PortType", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/GetNotificationCount")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WspGetNotificationCountPortType {


    /**
     * 
     * @param getNotificationCountRequest
     * @return
     *     returns DBGetNotificationCountClient.GetNotificationCountResponse
     * @throws Exception_Exception
     */
    @WebMethod(operationName = "ws_GetNotificationCount", action = "DNB_WebServices_Providers_GetNotificationCount_wsp_GetNotificationCount_Binder_ws_GetNotificationCount")
    @WebResult(name = "getNotificationCountResponse", targetNamespace = "")
    @RequestWrapper(localName = "ws_GetNotificationCount", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/GetNotificationCount", className = "DBGetNotificationCountClient.WsGetNotificationCount")
    @ResponseWrapper(localName = "ws_GetNotificationCountResponse", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/GetNotificationCount", className = "DBGetNotificationCountClient.WsGetNotificationCountResponse")
    public GetNotificationCountResponse wsGetNotificationCount(
        @WebParam(name = "getNotificationCountRequest", targetNamespace = "")
        GetNotificationCountRequest getNotificationCountRequest)
        throws Exception_Exception
    ;

}
