
package DBGetNotificationCountClient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "wsp_GetNotificationCount", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/GetNotificationCount", wsdlLocation = "WSDL/GetNotificationCount.wsdl")
public class WspGetNotificationCount
    extends Service
{

    private final static URL WSPGETNOTIFICATIONCOUNT_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(DBGetNotificationCountClient.WspGetNotificationCount.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = DBGetNotificationCountClient.WspGetNotificationCount.class.getResource("");
            url = new URL(baseUrl, "WSDL/GetNotificationCount.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'WSDL/GetNotificationCount.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSPGETNOTIFICATIONCOUNT_WSDL_LOCATION = url;
    }

    public WspGetNotificationCount(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WspGetNotificationCount() {
        super(WSPGETNOTIFICATIONCOUNT_WSDL_LOCATION, new QName("http://www.dnb.com/DNB_WebServices/Providers/GetNotificationCount", "wsp_GetNotificationCount"));
    }

    /**
     * 
     * @return
     *     returns WspGetNotificationCountPortType
     */
    @WebEndpoint(name = "DNB_WebServices_Providers_GetNotificationCount_wsp_GetNotificationCount_Port")
    public WspGetNotificationCountPortType getDNBWebServicesProvidersGetNotificationCountWspGetNotificationCountPort() {
        return super.getPort(new QName("http://www.dnb.com/DNB_WebServices/Providers/GetNotificationCount", "DNB_WebServices_Providers_GetNotificationCount_wsp_GetNotificationCount_Port"), WspGetNotificationCountPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WspGetNotificationCountPortType
     */
    @WebEndpoint(name = "DNB_WebServices_Providers_GetNotificationCount_wsp_GetNotificationCount_Port")
    public WspGetNotificationCountPortType getDNBWebServicesProvidersGetNotificationCountWspGetNotificationCountPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.dnb.com/DNB_WebServices/Providers/GetNotificationCount", "DNB_WebServices_Providers_GetNotificationCount_wsp_GetNotificationCount_Port"), WspGetNotificationCountPortType.class, features);
    }

}
