
package DBGetNotificationsClientV1;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "wsp_GetNotifications_V1", targetNamespace = "https://www.dnb.com/DNB_WebServices/Providers/GetNotifications_V1/wsp_GetNotifications_V1", wsdlLocation = "file:WSDL/GetNotifications_V1.wsdl")
public class WspGetNotificationsV1
    extends Service
{

    private final static URL WSPGETNOTIFICATIONSV1_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(DBGetNotificationsClientV1.WspGetNotificationsV1 .class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = DBGetNotificationsClientV1.WspGetNotificationsV1 .class.getResource(".");
            url = new URL(baseUrl, "file:WSDL/GetNotifications_V1.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:WSDL/GetNotifications_V1.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSPGETNOTIFICATIONSV1_WSDL_LOCATION = url;
    }

    public WspGetNotificationsV1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WspGetNotificationsV1() {
        super(WSPGETNOTIFICATIONSV1_WSDL_LOCATION, new QName("https://www.dnb.com/DNB_WebServices/Providers/GetNotifications_V1/wsp_GetNotifications_V1", "wsp_GetNotifications_V1"));
    }

    /**
     * 
     * @return
     *     returns WspGetNotificationsV1PortType
     */
    @WebEndpoint(name = "DNB_WebServices_Providers_GetNotifications_V1_wsp_GetNotifications_V1_Port")
    public WspGetNotificationsV1PortType getDNBWebServicesProvidersGetNotificationsV1WspGetNotificationsV1Port() {
        return super.getPort(new QName("https://www.dnb.com/DNB_WebServices/Providers/GetNotifications_V1/wsp_GetNotifications_V1", "DNB_WebServices_Providers_GetNotifications_V1_wsp_GetNotifications_V1_Port"), WspGetNotificationsV1PortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WspGetNotificationsV1PortType
     */
    @WebEndpoint(name = "DNB_WebServices_Providers_GetNotifications_V1_wsp_GetNotifications_V1_Port")
    public WspGetNotificationsV1PortType getDNBWebServicesProvidersGetNotificationsV1WspGetNotificationsV1Port(WebServiceFeature... features) {
        return super.getPort(new QName("https://www.dnb.com/DNB_WebServices/Providers/GetNotifications_V1/wsp_GetNotifications_V1", "DNB_WebServices_Providers_GetNotifications_V1_wsp_GetNotifications_V1_Port"), WspGetNotificationsV1PortType.class, features);
    }

}
