
package DBGetNotificationsClientV1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "wsp_GetNotifications_V1_PortType", targetNamespace = "https://www.dnb.com/DNB_WebServices/Providers/GetNotifications_V1/wsp_GetNotifications_V1")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WspGetNotificationsV1PortType {


    /**
     * 
     * @param getNotificationsRequest
     * @return
     *     returns DBGetNotificationsClientV1.GetNotificationsResponse
     */
    @WebMethod(operationName = "ws_GetNotifications", action = "DNB_WebServices_Providers_GetNotifications_V1_wsp_GetNotifications_V1_Binder_ws_GetNotifications")
    @WebResult(name = "getNotificationsResponse", targetNamespace = "")
    @RequestWrapper(localName = "ws_GetNotifications", targetNamespace = "https://www.dnb.com/DNB_WebServices/Providers/GetNotifications_V1/wsp_GetNotifications_V1", className = "DBGetNotificationsClientV1.WsGetNotifications")
    @ResponseWrapper(localName = "ws_GetNotificationsResponse", targetNamespace = "https://www.dnb.com/DNB_WebServices/Providers/GetNotifications_V1/wsp_GetNotifications_V1", className = "DBGetNotificationsClientV1.WsGetNotificationsResponse")
    public GetNotificationsResponse wsGetNotifications(
        @WebParam(name = "getNotificationsRequest", targetNamespace = "")
        GetNotificationsRequest getNotificationsRequest);

}
