
package DBAddRegistrationClient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "wsp_AddRegistration", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/AddRegistration", wsdlLocation = "file:WSDL/AddRegistration.wsdl")
public class WspAddRegistration
    extends Service
{

    private final static URL WSPADDREGISTRATION_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(DBAddRegistrationClient.WspAddRegistration.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = DBAddRegistrationClient.WspAddRegistration.class.getResource(".");
            url = new URL(baseUrl, "file:WSDL/AddRegistration.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:WSDL/AddRegistration.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSPADDREGISTRATION_WSDL_LOCATION = url;
    }

    public WspAddRegistration(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WspAddRegistration() {
        super(WSPADDREGISTRATION_WSDL_LOCATION, new QName("http://www.dnb.com/DNB_WebServices/Providers/AddRegistration", "wsp_AddRegistration"));
    }

    /**
     * 
     * @return
     *     returns WspAddRegistrationPortType
     */
    @WebEndpoint(name = "DNB_WebServices_Providers_AddRegistration_wsp_AddRegistration_Port")
    public WspAddRegistrationPortType getDNBWebServicesProvidersAddRegistrationWspAddRegistrationPort() {
        return super.getPort(new QName("http://www.dnb.com/DNB_WebServices/Providers/AddRegistration", "DNB_WebServices_Providers_AddRegistration_wsp_AddRegistration_Port"), WspAddRegistrationPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WspAddRegistrationPortType
     */
    @WebEndpoint(name = "DNB_WebServices_Providers_AddRegistration_wsp_AddRegistration_Port")
    public WspAddRegistrationPortType getDNBWebServicesProvidersAddRegistrationWspAddRegistrationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.dnb.com/DNB_WebServices/Providers/AddRegistration", "DNB_WebServices_Providers_AddRegistration_wsp_AddRegistration_Port"), WspAddRegistrationPortType.class, features);
    }

}
