
package DBAddRegistrationClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "wsp_AddRegistration_PortType", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/AddRegistration")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WspAddRegistrationPortType {


    /**
     * 
     * @param addRegistrationRequest
     * @return
     *     returns DBAddRegistrationClient.AddRegistrationResponse
     * @throws Exception_Exception
     */
    @WebMethod(operationName = "ws_AddRegistration", action = "DNB_WebServices_Providers_AddRegistration_wsp_AddRegistration_Binder_ws_AddRegistration")
    @WebResult(name = "addRegistrationResponse", targetNamespace = "")
    @RequestWrapper(localName = "ws_AddRegistration", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/AddRegistration", className = "DBAddRegistrationClient.WsAddRegistration")
    @ResponseWrapper(localName = "ws_AddRegistrationResponse", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/AddRegistration", className = "DBAddRegistrationClient.WsAddRegistrationResponse")
    public AddRegistrationResponse wsAddRegistration(
        @WebParam(name = "addRegistrationRequest", targetNamespace = "")
        AddRegistrationRequest addRegistrationRequest)
        throws Exception_Exception
    ;

}
