
package DBGetHQRegistrationListClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "wsp_GetHeadquarterRegistrationList_PortType", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/GetHeadquarterRegistrationList/wsp_GetHeadquarterRegistrationList")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WspGetHeadquarterRegistrationListPortType {


    /**
     * 
     * @param getHeadquarterRegistrationListRequest
     * @return
     *     returns DBGetHQRegistrationListClient.GetHeadquarterRegistrationListResponse
     */
    @WebMethod(operationName = "ws_GetHeadquarterRegistrationList", action = "DNB_WebServices_Providers_GetHeadquarterRegistrationList_wsp_GetHeadquarterRegistrationList_Binder_ws_GetHeadquarterRegistrationList")
    @WebResult(name = "getHeadquarterRegistrationListResponse", targetNamespace = "")
    @RequestWrapper(localName = "ws_GetHeadquarterRegistrationList", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/GetHeadquarterRegistrationList/wsp_GetHeadquarterRegistrationList", className = "DBGetHQRegistrationListClient.WsGetHeadquarterRegistrationList")
    @ResponseWrapper(localName = "ws_GetHeadquarterRegistrationListResponse", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/GetHeadquarterRegistrationList/wsp_GetHeadquarterRegistrationList", className = "DBGetHQRegistrationListClient.WsGetHeadquarterRegistrationListResponse")
    public GetHeadquarterRegistrationListResponse wsGetHeadquarterRegistrationList(
        @WebParam(name = "getHeadquarterRegistrationListRequest", targetNamespace = "")
        GetHeadquarterRegistrationListRequest getHeadquarterRegistrationListRequest);

}
