
package DBGetHQRegistrationListClient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "wsp_GetHeadquarterRegistrationList", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/GetHeadquarterRegistrationList/wsp_GetHeadquarterRegistrationList", wsdlLocation = "WSDL/GetHeadquarterRegistrationList.wsdl")
public class WspGetHeadquarterRegistrationList
    extends Service
{

    private final static URL WSPGETHEADQUARTERREGISTRATIONLIST_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(DBGetHQRegistrationListClient.WspGetHeadquarterRegistrationList.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = DBGetHQRegistrationListClient.WspGetHeadquarterRegistrationList.class.getResource("");
            url = new URL(baseUrl, "WSDL/GetHeadquarterRegistrationList.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'WSDL/GetHeadquarterRegistrationList.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSPGETHEADQUARTERREGISTRATIONLIST_WSDL_LOCATION = url;
    }

    public WspGetHeadquarterRegistrationList(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WspGetHeadquarterRegistrationList() {
        super(WSPGETHEADQUARTERREGISTRATIONLIST_WSDL_LOCATION, new QName("http://www.dnb.com/DNB_WebServices/Providers/GetHeadquarterRegistrationList/wsp_GetHeadquarterRegistrationList", "wsp_GetHeadquarterRegistrationList"));
    }

    /**
     * 
     * @return
     *     returns WspGetHeadquarterRegistrationListPortType
     */
    @WebEndpoint(name = "DNB_WebServices_Providers_GetHeadquarterRegistrationList_wsp_GetHeadquarterRegistrationList_Port")
    public WspGetHeadquarterRegistrationListPortType getDNBWebServicesProvidersGetHeadquarterRegistrationListWspGetHeadquarterRegistrationListPort() {
        return super.getPort(new QName("http://www.dnb.com/DNB_WebServices/Providers/GetHeadquarterRegistrationList/wsp_GetHeadquarterRegistrationList", "DNB_WebServices_Providers_GetHeadquarterRegistrationList_wsp_GetHeadquarterRegistrationList_Port"), WspGetHeadquarterRegistrationListPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WspGetHeadquarterRegistrationListPortType
     */
    @WebEndpoint(name = "DNB_WebServices_Providers_GetHeadquarterRegistrationList_wsp_GetHeadquarterRegistrationList_Port")
    public WspGetHeadquarterRegistrationListPortType getDNBWebServicesProvidersGetHeadquarterRegistrationListWspGetHeadquarterRegistrationListPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.dnb.com/DNB_WebServices/Providers/GetHeadquarterRegistrationList/wsp_GetHeadquarterRegistrationList", "DNB_WebServices_Providers_GetHeadquarterRegistrationList_wsp_GetHeadquarterRegistrationList_Port"), WspGetHeadquarterRegistrationListPortType.class, features);
    }

}
