
package DBWebClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "wsp_LookUp_PortType", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/LookUp")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WspLookUpPortType {


    /**
     * 
     * @param lookUpRequest
     * @return
     *     returns DBWebClient.LookUpResponse
     * @throws Exception_Exception
     */
    @WebMethod(operationName = "ws_LookUp", action = "DNB_WebServices_Providers_LookUp_wsp_LookUp_Binder_ws_LookUp")
    @WebResult(name = "lookupResponse", targetNamespace = "")
    @RequestWrapper(localName = "ws_LookUp", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/LookUp", className = "DBWebClient.WsLookUp")
    @ResponseWrapper(localName = "ws_LookUpResponse", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/LookUp", className = "DBWebClient.WsLookUpResponse")
    public LookUpResponse wsLookUp(
        @WebParam(name = "lookUpRequest", targetNamespace = "")
        LookUpRequest lookUpRequest)
        throws Exception_Exception
    ;

}
