
package DBDataWebClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "wsp_GDP_PortType", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/OrderAndInvestigations/GDP/wsp_GDP")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WspGDPPortType {


    /**
     * 
     * @param gdpRequest
     * @return
     *     returns DBDataWebClient.GDPResponse
     */
    @WebMethod(operationName = "ws_OtherGDPProducts", action = "DNB_WebServices_Providers_OrderAndInvestigations_GDP_wsp_GDP_Binder_ws_OtherGDPProducts")
    @WebResult(name = "GDPResponse", targetNamespace = "")
    @RequestWrapper(localName = "ws_OtherGDPProducts", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/OrderAndInvestigations/GDP/wsp_GDP", className = "DBDataWebClient.WsOtherGDPProducts")
    @ResponseWrapper(localName = "ws_OtherGDPProductsResponse", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/OrderAndInvestigations/GDP/wsp_GDP", className = "DBDataWebClient.WsOtherGDPProductsResponse")
    public GDPResponse wsOtherGDPProducts(
        @WebParam(name = "GDPRequest", targetNamespace = "")
        ProdOrderRequest gdpRequest);

    /**
     * 
     * @param corporateLinkageRequest
     * @return
     *     returns DBDataWebClient.CorporateLinkageResponse
     */
    @WebMethod(operationName = "ws_CorporateLinkage", action = "DNB_WebServices_Providers_OrderAndInvestigations_GDP_wsp_GDP_Binder_ws_CorporateLinkage")
    @WebResult(name = "corporateLinkageResponse", targetNamespace = "")
    @RequestWrapper(localName = "ws_CorporateLinkage", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/OrderAndInvestigations/GDP/wsp_GDP", className = "DBDataWebClient.WsCorporateLinkage")
    @ResponseWrapper(localName = "ws_CorporateLinkageResponse", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/OrderAndInvestigations/GDP/wsp_GDP", className = "DBDataWebClient.WsCorporateLinkageResponse")
    public CorporateLinkageResponse wsCorporateLinkage(
        @WebParam(name = "corporateLinkageRequest", targetNamespace = "")
        ProdOrderRequest corporateLinkageRequest);

    /**
     * 
     * @param gdmRequest
     * @return
     *     returns DBDataWebClient.GDMResponse
     */
    @WebMethod(operationName = "ws_GDM", action = "DNB_WebServices_Providers_OrderAndInvestigations_GDP_wsp_GDP_Binder_ws_GDM")
    @WebResult(name = "gdmResponse", targetNamespace = "")
    @RequestWrapper(localName = "ws_GDM", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/OrderAndInvestigations/GDP/wsp_GDP", className = "DBDataWebClient.WsGDM")
    @ResponseWrapper(localName = "ws_GDMResponse", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/OrderAndInvestigations/GDP/wsp_GDP", className = "DBDataWebClient.WsGDMResponse")
    public GDMResponse wsGDM(
        @WebParam(name = "gdmRequest", targetNamespace = "")
        ProdOrderRequest gdmRequest);

    /**
     * 
     * @param globalProdERamRequest
     * @return
     *     returns DBDataWebClient.GlobalProdEramResponse
     */
    @WebMethod(operationName = "ws_GlobalProduct_eRam", action = "DNB_WebServices_Providers_OrderAndInvestigations_GDP_wsp_GDP_Binder_ws_GlobalProduct_eRam")
    @WebResult(name = "globalProd_eRamResponse", targetNamespace = "")
    @RequestWrapper(localName = "ws_GlobalProduct_eRam", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/OrderAndInvestigations/GDP/wsp_GDP", className = "DBDataWebClient.WsGlobalProductERam")
    @ResponseWrapper(localName = "ws_GlobalProduct_eRamResponse", targetNamespace = "http://www.dnb.com/DNB_WebServices/Providers/OrderAndInvestigations/GDP/wsp_GDP", className = "DBDataWebClient.WsGlobalProductERamResponse")
    public GlobalProdEramResponse wsGlobalProductERam(
        @WebParam(name = "globalProd_eRamRequest", targetNamespace = "")
        ProdOrderRequest globalProdERamRequest);

}
